image:
  repository: stakkato95/twitter-service-users
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  httpPort: 80
  grpcPort: 90

ingress:
  enabled: true
