apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-node-port
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 32222
      protocol: TCP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
